# Setup
title:        Blogs | Nikhil Mehta
tagline:      Blogs hosted on GitHub using Jekyll Theme
baseurl:      "/blogs"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Nikhil Mehta
  url:        http://www3.cs.stonybrook.edu/~nsmehta/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
