# Setup
title:        Blogs | Nikhil Mehta
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "http://nsmehta.github.io/blogs"
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://nsmehta.github.io/blogs

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
